mqtt:
  server: 127.0.0.1
  port: 1883
  uid: yeelight_gateway
  username: mqttuser
  password: passw0rd
  topic: home/{group}

sids:
  # lamps
  192.168.1.51:
    name: main-mono
    group: room
    effect: "smooth"
    duration: 300
  192.168.1.54:
    name: main-color
    music_mode:
      ip: 192.168.0.5
      port: 45530
  192.168.1.52:
    name: main
    group: kitchen
  192.168.1.53:
    name: hall

interval: 2
json_payload: false
default_group: "light"